### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/levelup#1]
- [x] category label design in Cat-1

- [x] Apply the padding and margins from the category options

- [x] Cat 3 small posts design

- [x] cat 4 heading should be normal

- [x] cat 5 - meta info design

- [x] cat 6  category label should be aligned with the image. 

- [x] cat 7 design properly.

- [x] create demos of the blocks

 

- [x] width of the module container is not applied by default, find out why! 

- [x] Modal design

_________

- [x] AMP CSS is not loading.  (Ajeet)

- [x] We need to generate thumbnails according to the correct design. (Ajeet)

- [x] Hide the Design Library Post type.

- [x] Create the options panel where we will have the sync the library option

- [x] Notice will only show if the new version is available. To check, we have to go into the panel

- [x] After the activation, There should be a notice. It will say "Congratulations on installing Elementor Plus. You have one last step remaining to finish the installation." - with a button, "Finish Installation" - When they click on this, it will take them to an options panel where they have to enter the API key, On First Sucessful API key activation, it should directly sync the library with the sync option, - The whole thing will visually look like the Tools page of the Elementor Options. 

- [x] Lets say user has synced first time. Now version 2 is available, how we will show them the notification of it?

- [ ] If a user just installs the plugin and comes directly to the Elementor, then they should see the message with link where they can finish the installation: https://monosnap.com/file/yWl4zLJhp6ugTxtuSV3nBuBDrH6R7W

- [x] Setup the actual library on E-plus server (Ahmed)

- [x] At the place of except the error is showing, which is coming from the AMP Wordpress Theme.
https://monosnap.com/file/cP7Q00BXygE7ljp4W7fYkM6rYmM6Ua
- [x] Add uninstall.php remove CUSTOM POST,Taxonomy and options
- [x] change the server URL AFTER SETUP E-PLUS server in client plugin

- [x] When elementor is in production (mode), Elementor plus plugin show an error, see this
![12](https://user-images.githubusercontent.com/24938279/44942884-42801980-add9-11e8-8940-cc4c9c2f5235.png)
https://monosnap.com/file/bXSekdF8NH33NQdqYZvnpP7qIfVvLE

- [x] When API is not entered, in the Elementor plus plugin, need to show the finial installation text with link, it will redirect to get api link and settings text with  link, please check this.
https://monosnap.com/file/tCP2MNFsehbDgt2OYm0x0bW09gT2lr

**Comment by ahmedkaludi** [comment]
done
